char appart[] =  
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"x          x                             x       x"
"x     xxxx x  x                     x    x   x   x"
"x     xxxx x  x                          x   x   x"
"x     x    x  x                     xxxxxxxxxxx  x"
"x     xxxxxxx xxxxxxxxxxxxxxxxxxxxx xxx  x       x"
"x                                                x"
"x          x                             x       x"
"x          x                             x       x"
"x          xxxxxxxxxx                    x       x"
"xxxxxxxxxx x                             xxxxxxxxx"
"x          x                        xxxxxxxxxxxxxx"
"x          xxxxxxxxxx               x            x"
"x          x                        x            x"
"x          x                        x            x"
"x          xxxxx                    x            x"
"x                                   xxxxxx       x"
"x          xxxxx                         x       x"
"x          x                                     x"
"x          x                             x       x"
"x          x                             x       x"
"x          x                        x            x"
"x          x                        x            x"
"x          xxxxx                    x            x"
"x                                   xxxxxx       x"
"x          xxxxx                         x       x"
"x          x                                     x"
"x          x                             x       x"
"x          x                             x       x"
"x          x                        x            x"
"x          x                        x            x"
"x          xxxxx                    x            x"
"x              x                    xxxxxx       x"
"x          xxxxx                         x       x"
"x          x                                     x"
"x          x                             x       x"
"x          x                             x       x"
"x          x                        xxxxxx       x"
"x          x                        x            x"
"x          xxxxx                    x            x"
"x                                   xxxxxx       x"
"x          xxxxx                         x       x"
"x          x                                     x"
"x          x                        xxxxxxx      x"
"x          x                        x     x      x"
"x     xxxxxx                        x          x x"
"x     x    x                        x    xxxxxxx x"
"x     x    xxxxx                    x    x       x"
"x          x                        x            x"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxSxxxxxxxxxxx";
