/* Original map */

char appart[] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"x                                                x"
"x                                                x"
"x                 xxxxxxxxxxxx                   x"
"xxxxxxxxxxxxxxxxxxx          x                   x"
"x                            x                   x"
"x                            x                   x"
"x                            x                   x"
"x         x                  x                   x"
"x         x                  xxxxxx        xxxxxxx"
"x         x                                      x"
"x         x                                      x"
"x         x                                      x"
"x                                                x"
"x                                                x"
"xxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxx"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                x                               x"
"x               x x                              x"
"x              x   x                             x"
"x             x     x                            x"
"x              x   x                             x"
"x               x x                              x"
"x                x                               x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x            x                                   x"
"x            x                                   x"
"x            x                                   x"
"x            x                                   x"
"x            x                                   x"
"x            x                                   x"
"x            x                                   x"
"x            x             xxxxxxxxxxxxxxxxxxxxxxx"
"x            x                                   S"
"x            x                                   x"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
