#ifndef APPART_H
#define APPART_H

char appart[] = 
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"xxxxxxxxxxxxxx     x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"xxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxx"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                                                x"
"x                                                x"
"x                                                x"
"x          xxxxxxxxx         x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"xxxxxxSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

#endif

