#define HAUTEUR 50
#define LARGEUR 50

char appart[]=
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"x                x                               x"
"x                x                               x"
"x                x                               x"
"x                x                               x"
"x                x                               x"
"x                x                               x"
"x                x          xxxxxxxxxxxxxxxxxxxxxx"
"x                x                               x"
"x                x          x   x   x            x"
"x                x           x x x x             x"
"x                x            x   x              x"
"x                                                x"
"x                             xxxxx              x"
"x                             x   x              x"
"xxxxxxxxxxxxxxxxx             x   x              x"
"x                             xxxxx              x"
"xxxxxxxxxxxxxxxxx                                x"
"xxxxxxxxx                   x   x   x            x"
"x       x                    x x x x             x"
"x       x                     x   x              x"
"x       x     xxxxxxxxxxx                        x"
"x       x                                        x"
"x       x                                        x"
"x       x              x                         x"
"x       x              x                         x"
"x                      x                         x"
"x                      x                         x"
"x                      x                         x"
"x      xxxxxxxxxxx     x                         x"
"x                      x                         x"
"x                      x                         x"
"x                      x       xxxxxxxxxxxxxxxxxxx"
"x     xxxxxxxxxx       x                         x"
"x     x        x       x                         x"
"x     x   xx   x       x                         x"
"x     x   xS   x       x                         x"
"x     x        x       x                         x"
"x     xxxxxxxxxx       x                         x"
"x                      x                         x"
"x                      x                         x"
"x                      x                         x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
