#ifndef APPART_H
#define APPART_H

char appart[] = 
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxSxxxxxxxxxxxxx"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            x                     x             x"
"x            xxxxxxxxxxxxxxxxxxxxxxx             x"
"x                                                x"
"x                                                x"
"x                                                x"
"x                                                x"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

#endif

