#ifndef APPART_H
#define APPART_H

char appart[] = 
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxSxxxxxxxxxxxxxxxxx"
"x                  x         x                   x"
"x xxxxxx           x         x                   x"
"x x    x           x         x                   x"
"x xxxxxx           x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"xxxxxxxxxxxxxx     x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                            x                   x"
"x                            x                   x"
"x                            x                   x"
"x                            x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"xxxxxxxxxxxxxxxxxxxx         xxxxxxxxxx     xxxxxx"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                  x         x                   x"
"x                            x                   x"
"x                            x                   x"
"x                            x                   x"
"x          xxxxxxxxx         x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          x                 x                   x"
"x          xxxxxxxxxxxxxxxxxxx                   x"
"x                                                x"
"x                                                x"
"x                                                x"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

#endif

