#ifndef HELL
#define HELL

char appart[] =
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"x            x                                   x"
"x            x                     xxxxxxxxxxxx  x"
"x            xxxxxxxxxxxxxxxxxxxxx x          x  x"
"x            x                     x          x  x"
"x            x                     x          x  x"
"x            x                     x          x  x"
"x            x xxxxxxxxxxxxxxxxxxxxx          x  x"
"x            x                x    x          x  x"
"x            x              x x  x x          x  x"
"x            x              x x  x x          x  x"
"x            x              x x  x x          x  x"
"x            xxxxxxxxxxxxxxxx x  x x          x  x"
"x            x                   x x          x  x"
"x            xxxxxxxxxxxxxxxxxxxxx x          x  x"
"x            x                     x          x  x"
"x            xx xxxxxxxxxxxxxxxxxxxx          x  x"
"x            x                     x          x  x"
"x            xxxxxxxxxx xxxxxxxxxxxx          x  x"
"x            x                     x          x  x"
"x            xxxxxxx xxxxxxxxxxxxxxx          x  x"
"x x          x     x x             x          x  x"
"x x          x     x x             x          x  x"
"x x          x     x x             x          x  x"
"x x          x     x x             x          x  x"
"x x          x     x x             x          x  x"
"x x          x     x x             x          x  x"
"x x       xxxx     x x             x          x  x"
"x xxx xxx    xxxxxxx x             x          x  x"
"x     xSx            x             x          x  x"
"xxxxxxx xxxxxxxxxxxxxx             x          x  x"
"x     x x    x                     x          x  x"
"x xxxxx x    x                     x          x  x"
"x       x    x                     x          x  x"
"x  xxxxxx    x                     x          x  x"
"x  x         x                     x          x  x"
"x  x         x                     x          x  x"
"x  x         x                     xxxxxxxxxxxx  x"
"x  x         x                   x x             x"
"x  x         x           xxxxxx  xxx  xxxxxxxxxxxx"
"x  x      x  x           x                       x"
"x  x      x xx           x xxxxxxxxx   xxxxxxxxxxx"
"x  x      x xx           x x       x   x         x"
"x  x      x xx           x x       xx  x         x"
"x  x  xxxxx xxxxxxxxxxxxx  x       x  xx         x"
"x  x  x                 x  x       x   x         x"
"x  x  x xxxxxxxxxxxxxxxxxx x                     x"
"x  xxxx xxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxx"
"x                                                x"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

#endif
