#ifndef HELL
#define HELL

char appart[] =
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
"x            x    xx       x                     x"
"x          x x   x  x     x        xxxxxxxxxxxx  x"
"x         x  x  x    x    x        x          x  x"
"xx       x   x x      x  x         x          x  x"
"x x     x   xxx        xx          x          x  x"
"x  x    x  x x                     x          x  x"
"x   x  x   x x xxxxxxxxxxxxxxxxxxxxx          x  x"
"x    xx   x  x                x    x          x  x"
"x            x              x x  x x          x  x"
"xxxxxxxxxxxx x              x x  x x          x  x"
"x            x              x x  x x          x  x"
"x      x    xxxxxxxxxxxxxxxxx x  x x          x  x"
"x     x x  x x                   x x          x  x"
"x    x  xxxxxxxxxxxxxxxxxxxxxxxxxx x          x  x"
"x   x      x x                     x   x  x   x  x"
"x  x         xx xxxxxxxxxxxxxxxxxxxx   x  x   x  x"
"x            x                     x   x  x   x  x"
"xxxxxxxx     xxxxxxxxxx xxxxxxxxxxxx   x  x   x  x"
"x            x                     xxxxx  xxxxx  x"
"x         x  xxxxxxx  x                          x"
"x x      x   x     x x x           x  xxxxxxxxx  x"
"x x     x    x     x x             x          x  x"
"x x    x     x     x x  x  xxx x   x          x  x"
"x x x  x     x     x x  x  x x x   x          x  x"
"x x  x  x    x     x x  xx xxx xx  x          x  x"
"x x   x  x   x     x x             x          x  x"
"x x    x  xxxx     x xxxxxxxxxxxx xx          x  x"
"x xxx xxx    xxxxxxx x             x          x  x"
"x     xSx            x   xx        x          x  x"
"xxxxxxx xxxxxx xxxxxxx  xxxx       x          x  x"
"x     x x    x x        xxxx       x          x  x"
"x xxxxx x    x x     xxxxxxxxxx    x          x  x"
"x       x    x x     x   xx   x    x          x  x"
"x  xxxxxx    x x     x   xx   x    x          x  x"
"x  x    x    x x     xxxxxxxxxx    x          x  x"
"x  x xxx     x x                   x          x  x"
"x    x       x x                   xxxxxxxxxxxx  x"
"x  x x       x x              x x  x             x"
"x  x x       x x       x xxxxxxx xxx  xxxxxxxxxxxx"
"x  x x       x x      x  x                       x"
"x  x x    x xx x      x  x xxxxxxxxx   xxxxxxxxxxx"
"x  x x    x xx xxxxxxxx  x x       x   x         x"
"x  x x    x xx           x x       xx  x         x"
"x  x  xxxxx xxxxxxxxxxxxx  x       x  xx         x"
"x  x  x                 x  x       x   x         x"
"x  x  x xxxxxxxxxxxxxxxxxx x                     x"
"x  xxxx xxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxx"
"x                                                x"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

#endif
